# Instancia de Evaluación Espacio de entrega de tarea:


En el emocionante campo de la Ciencia de Datos, uno de los primeros pasos es la importación y manipulación efectiva de datos. La librería PANDAS en Python es una herramienta esencial para llevar a cabo esta tarea, ya que proporciona funciones y estructuras de datos que permiten la limpieza, transformación y análisis de datos de manera eficiente.

Imaginemos que eres un científico de datos que trabaja en un proyecto de análisis de mercado para una empresa de comercio electrónico. Tu objetivo es recopilar, procesar y analizar datos de ventas que provienen de diferentes fuentes en varios formatos. Para lograrlo, debes diseñar un proceso de importación de datos utilizando PANDAS.

## Datos de Prueba:
- Archivo CSV (Comma-Separated Values): Tienes un archivo llamado "ventas.csv" que contiene información sobre las ventas de productos. Cada fila representa una venta y contiene varias columnas con los datos sobre las ventas.

- Archivo JSON (JavaScript Object Notation): También tienes un archivo llamado "clientes.json" con datos de los clientes que realizaron las compras. Cada objeto JSON representa un cliente y contiene sus datos.

- Hoja de Cálculo Excel: Existe un archivo llamado "inventario.xlsx" con información sobre el inventario de productos. La hoja de cálculo contiene varias columnas con datos sobre los productos.

Tu tarea es utilizar la librería PANDAS para importar estos datos desde los diferentes formatos (CSV, JSON y Excel), combinarlos en una estructura de datos adecuada y realizar las siguientes acciones:

Cargar los datos de ventas desde el archivo CSV y mostrar una vista previa de las primeras filas.

Cargar los datos de clientes desde el archivo JSON y mostrar la cantidad total de clientes.

Cargar los datos de inventario desde la hoja de cálculo Excel y calcular el promedio de stock disponible para todos los productos.

**importo pandas:**

In [28]:
import pandas as pd

**1. Cargar los datos de ventas desde el archivo CSV y mostrar una vista previa de las primeras filas.**

In [29]:
ventas = pd.read_csv('ventas (1).csv')
ventas

   id_venta       fecha  producto  cantidad  precio_unitario
0         1  2026-01-10  Notebook         2             1200
1         2  2026-01-12     Mouse         5               25
2         3  2026-01-15   Teclado         3               45
3         4  2026-01-18   Monitor         1              300

In [30]:
ventas.head()

   id_venta       fecha  producto  cantidad  precio_unitario
0         1  2026-01-10  Notebook         2             1200
1         2  2026-01-12     Mouse         5               25
2         3  2026-01-15   Teclado         3               45
3         4  2026-01-18   Monitor         1              300

**2. Cargar los datos de clientes desde el archivo JSON y mostrar la cantidad total de clientes.**

In [31]:
clientes = pd.read_json('clientes.json')
clientes

   id_cliente        nombre             email   telefono
0           1    Juan Pérez    juan@email.com  123456789
1           2   María López   maria@email.com  987654321
2           3  Carlos Gómez  carlos@email.com  456123789

In [32]:
len(clientes)

3

**3. Cargar los datos de inventario desde la hoja de cálculo Excel y calcular el promedio de stock disponible para todos los productos.**

In [33]:
inventario = pd.read_excel('inventario.xlsx')
inventario

   id_producto    nombre    categoria  stock  precio
0            1  Notebook  Electrónica     10    1200
1            2     Mouse   Accesorios     50      25
2            3   Teclado   Accesorios     30      45
3            4   Monitor  Electrónica     15     300

In [34]:
inventario['stock'].mean()

np.float64(26.25)